# Site settings
title: Donato Rimenti
description: Donato Rimenti Website
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aurasphere.co" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Donato Rimenti
user_description: Work in progress
user_title: Software Architect / Full Stack Developer
email: donatohan.rimenti@gmail.com
github_url: https://github.com/aurasphere
linkedin_url: https://www.linkedin.com/in/donato-rimenti-764876132/
stackoverflow_url: https://stackoverflow.com/users/4921205/aurasphere
baeldung_url: https://www.baeldung.com/author/donato-rimenti/
google_play_store_url: https://play.google.com/store/apps/dev?id=5166715628155281634
maven_url: https://search.maven.org/search?q=g:co.aurasphere.*

exclude: ['package.json', 'src' , 'node_modules']
